version: "3.8"

services:
  app:
    build:
      context: .
      target: dev  # Use the dev stage for local development
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app  # Syncs local files with the container
      - /app/node_modules  # Prevents overwriting node_modules
    command: ["npm", "run", "dev"]  # Runs nodemon for live-reloading






