export default class MobileAddsProduct {
  manufacturer_name: string;
  height: string;
  available_for_order: string;
  reference: string;
  upc: string;
  ean13: string;
  supplier_reference: string;
  supplier_id: string;
  product_id: string;
  manufacturer_id: string;
  location: string;
  weight: string;
  depth: string;
  out_of_stock: string;
  width: string;
  on_sale: string;
  active: string;
  date_add: string;
  date_upd: string;
  price: string;
  wholesale_price: string;
  ecotax: string;
  quantity: string;
  quantity_discount: string;
  category_default_id: string;
  available_later: string;
  available_now: string;
  name: string;
  meta_title: string;
  meta_keywords: string;
  meta_description: string;
  link_rewrite: string;
  description_short: string;
  description: string;
  category_default_name: string;
  price_shipping: string;
  price_sale: string;
  product_url: string;

  constructor(data: any) {
    this.manufacturer_name = data.manufacturer_name[0];
    this.height = data.height[0];
    this.available_for_order = data.available_for_order[0];
    this.reference = data.reference[0];
    this.upc = data.upc[0];
    this.ean13 = data.ean13[0];
    this.supplier_reference = data.supplier_reference[0];
    this.supplier_id = data.supplier_id[0];
    this.product_id = data.product_id[0];
    this.manufacturer_id = data.manufacturer_id[0];
    this.location = data.location[0];
    this.weight = data.weight[0];
    this.depth = data.depth[0];
    this.out_of_stock = data.out_of_stock[0];
    this.width = data.width[0];
    this.on_sale = data.on_sale[0];
    this.active = data.active[0];
    this.date_add = data.date_add[0];
    this.date_upd = data.date_upd[0];
    this.price = data.price[0];
    this.wholesale_price = data.wholesale_price[0];
    this.ecotax = data.ecotax[0];
    this.quantity = data.quantity[0];
    this.quantity_discount = data.quantity_discount[0];
    this.category_default_id = data.category_default_id[0];
    this.available_later = data.available_later[0];
    this.available_now = data.available_now[0];
    this.name = data.name[0];
    this.meta_title = data.meta_title[0];
    this.meta_keywords = data.meta_keywords[0];
    this.meta_description = data.meta_description[0];
    this.link_rewrite = data.link_rewrite[0];
    this.description_short = data.description_short[0];
    this.description = data.description[0];
    this.category_default_name = data.category_default_name[0];
    this.price_shipping = data.price_shipping[0];
    this.price_sale = data.price_sale[0];
    this.product_url = data.product_url[0];
  }
}
